adti-addiction:
  request-url: 42.62.96.68
  port: 8080
  # 不用加'/'
  loginParameter: login
  payParameter: pay
  key:
  loginJsonKey:
  payJsonKey:

task:
  pool:
    carePollSize: 20
    maxPoolSize: 750
    keepAliveSeconds: 3000
    queueCapacity: 50